### ISSUE TITLE
Static property HelloWorld::$tempDir is never read, only written.

### ISSUE THREAD

**Issue by kamil-tekiela** [phpstan/phpstan-src#2440]
https://phpstan.org/r/cdfbef75-f51b-4911-ab87-b313acd4c47f

I don't understand what PHPStan is complaining about here because it is definitely read from. I tested it and it works as designed. When I change the read line to use `self` instead of `$this` PHPstan no longer complains, but why would that ever make a difference? It's still the same code.

**Comment by ondrejmirtes** [comment]
Please open the bug report in phpstan/phpstan.
