### ISSUE TITLE
Suppress "Using configuration file" in combination with --error-format

### ISSUE THREAD

**Issue by shaedrich** [phpstan/phpstan-src#2443]
When using `--error-format` command line option, the output of the command might be redirected to a file. Both JSON and XML format require their contents to be formatted in a certain way. However, when using a configuration file by passing the `-c` option or using [larastan](https://github.com/nunomaduro/larastan), the line "Using configuration file" is printed at the first line of the file which makes it invalid. The progress bar can be suppressed by passing `--no-progress` but I couldn't find a way to suppress the "Using configuration file" line since `-q` option also suppresses the output that is supposed to go into that very file, creating it empty.

Am I missing something here and this is easily avoidable or is this something that has to be fixed?

https://github.com/phpstan/phpstan-src/blob/d94a80d1295457d03cdd58764d35ec1080cb6973/src/Command/CommandHelper.php#L170

**Comment by ondrejmirtes** [comment]
Some output is printed to `stdout` and some to `stderr`. If you're interested in machine readable format, read only `stdout`.

And please next time you open an issue, do it in `phpstan/phpstan`. Thanks.

**Comment by shaedrich** [comment]
Thank you, I'll keep that in mind
