### ISSUE TITLE
empty() and isnull() -> Negated boolean expression is always true.

### ISSUE THREAD

**Issue by Balkoth** [phpstan/phpstan-src#2510]
The following code leads to analyzer to the error `Negated boolean expression is always true.`

```php
if (!empty($_POST["SAMPLE"]) && !is_null($_POST["SAMPLE"]))
{
}
```

If checking with array_key_exists this problem does not exist.

**Comment by ondrejmirtes** [comment]
`empty($foo)` is `!isset($foo) || $foo == false`.

Which means that `!empty($foo)` is `isset($foo) && $foo != false`.

`isset($foo)` for `$foo` being `null` is false.

So yeah, `!empty($foo) && !is_null($foo)` is not necessary.
